// code generated by pbf v4.0.1

export function readGeo(pbf, end) {
    return pbf.readFields(readGeoField, {lat: "", lng: ""}, end);
}
function readGeoField(tag, obj, pbf) {
    if (tag === 1) obj.lat = pbf.readString();
    else if (tag === 2) obj.lng = pbf.readString();
}
export function writeGeo(obj, pbf) {
    if (obj.lat) pbf.writeStringField(1, obj.lat);
    if (obj.lng) pbf.writeStringField(2, obj.lng);
}

export function readAddress(pbf, end) {
    return pbf.readFields(readAddressField, {street: "", suite: "", city: "", zipcode: "", geo: undefined}, end);
}
function readAddressField(tag, obj, pbf) {
    if (tag === 1) obj.street = pbf.readString();
    else if (tag === 2) obj.suite = pbf.readString();
    else if (tag === 3) obj.city = pbf.readString();
    else if (tag === 4) obj.zipcode = pbf.readString();
    else if (tag === 5) obj.geo = readGeo(pbf, pbf.readVarint() + pbf.pos);
}
export function writeAddress(obj, pbf) {
    if (obj.street) pbf.writeStringField(1, obj.street);
    if (obj.suite) pbf.writeStringField(2, obj.suite);
    if (obj.city) pbf.writeStringField(3, obj.city);
    if (obj.zipcode) pbf.writeStringField(4, obj.zipcode);
    if (obj.geo) pbf.writeMessage(5, writeGeo, obj.geo);
}

export function readCompany(pbf, end) {
    return pbf.readFields(readCompanyField, {name: "", catchPhrase: "", bs: ""}, end);
}
function readCompanyField(tag, obj, pbf) {
    if (tag === 1) obj.name = pbf.readString();
    else if (tag === 2) obj.catchPhrase = pbf.readString();
    else if (tag === 3) obj.bs = pbf.readString();
}
export function writeCompany(obj, pbf) {
    if (obj.name) pbf.writeStringField(1, obj.name);
    if (obj.catchPhrase) pbf.writeStringField(2, obj.catchPhrase);
    if (obj.bs) pbf.writeStringField(3, obj.bs);
}

export function readUser(pbf, end) {
    return pbf.readFields(readUserField, {id: 0, name: "", username: "", email: "", address: undefined, phone: "", website: "", company: undefined}, end);
}
function readUserField(tag, obj, pbf) {
    if (tag === 1) obj.id = pbf.readVarint();
    else if (tag === 2) obj.name = pbf.readString();
    else if (tag === 3) obj.username = pbf.readString();
    else if (tag === 4) obj.email = pbf.readString();
    else if (tag === 5) obj.address = readAddress(pbf, pbf.readVarint() + pbf.pos);
    else if (tag === 6) obj.phone = pbf.readString();
    else if (tag === 7) obj.website = pbf.readString();
    else if (tag === 8) obj.company = readCompany(pbf, pbf.readVarint() + pbf.pos);
}
export function writeUser(obj, pbf) {
    if (obj.id) pbf.writeVarintField(1, obj.id);
    if (obj.name) pbf.writeStringField(2, obj.name);
    if (obj.username) pbf.writeStringField(3, obj.username);
    if (obj.email) pbf.writeStringField(4, obj.email);
    if (obj.address) pbf.writeMessage(5, writeAddress, obj.address);
    if (obj.phone) pbf.writeStringField(6, obj.phone);
    if (obj.website) pbf.writeStringField(7, obj.website);
    if (obj.company) pbf.writeMessage(8, writeCompany, obj.company);
}

export function readUsers(pbf, end) {
    return pbf.readFields(readUsersField, {users: []}, end);
}
function readUsersField(tag, obj, pbf) {
    if (tag === 1) obj.users.push(readUser(pbf, pbf.readVarint() + pbf.pos));
}
export function writeUsers(obj, pbf) {
    if (obj.users) for (const item of obj.users) pbf.writeMessage(1, writeUser, item);
}
